#%RAML 1.0 NamedExample
create-employee:

  {
        "employees":[
          {
         "firstName": "Pradeep Kumar",
         "lastName": "N",
         "dateOfBirth": "1982-11-22",
         "dateOfJoining": "2018-10-10",
         "mobile":7093902213,
         "email": "pradeep.n2019@gmail.com",
         "department": "IT-Software"
        }]
        }