#%RAML 1.0 NamedExample
get-employees:
   {
        "employees":[
          {
         "employeeId":"",
         "firstName": "Pradeep Kumar",
         "lastName": "N",
         "dateOfBirth": "22-11-1982",
         "dateOfJoining": "20-10-2018",
         "mobile":7093902213,
         "department": "IT-Software"
        }]
        }