#%RAML 1.0
title: Employee System API
types:
  Employee:
    type: object
    displayName: Employee record details
    
    properties:
      firstName: string
      lastName: string
      dateOfBirth: date-only
      dateOfJoining: date-only
      mobile: number
      email: string
      department: string

  Employees:
    properties:
      employees: Employee[]
        
/employees:
  description: Employees Details
    
  post:
    description: Add a new Employee
    body: 
     application/json:
       description: submit group of employee as a list
       type: Employees
      
    responses:
     200:
      body:
        application/json:
          examples:
           examples: !include examples/create-employee.raml

  /{employeeID}:
    description: A single employee details
    uriParameters:
      employeeID:
        description: Employee ID
        type: integer
        
    get:
      description: View a single employee details by Employee ID
      responses:
        200:
          body:
            application/json:
              examples: !include examples/get-employees.raml
             
             
       